from Vector import Vector

# Constants that will be accessed throughout project
# World Constants
FRAME_RATE = 60
WORLD_WIDTH = 1024
WORLD_HEIGHT = 768
BACKGROUND_COLOR = (100, 149, 237)
SCREEN_SIZE = Vector(WORLD_WIDTH, WORLD_HEIGHT)
BOUNDRY_RADIUS = 50
BOUNDRY_WEIGHT = 1

# Player Constants
PLAYER_SIZE = Vector(16, 32)
PLAYER_SPEED = 5.5
PLAYER_COLOR = (255, 229, 44)
PLAYER_WEIGHT = .5
PLAYER_TURN_SPEED= .4

# Enemy Constants
ENEMY_SIZE = Vector(16,32)
ENEMY_SPEED = 5
ENEMY_COLOR = (79, 201, 0)
MIN_ATTACK_DIST = 200
SHEEP_FLEE_WEIGHT = .5
SHEEP_WANDER_WEIGHT = .5
SHEEP_TURN_SPEED = .35
SHEEP_BOUNDARY_WEIGHT = .5
SHEEP_DOG_WEIGHT = .4
SHEEP_ALIGNMENT_WEIGHT = .4
SHEEP_SEPERATION_WEIGHT = .3
SHEEP_COHESION_WEIGHT = .4
SHEEP_NEIGHBOR_RADIUS = 50
SHEEP_BOUNDARY_RADIUS = 50



# Agent Constants
AGENT_WIDTH = 16.0
AGENT_HEIGHT = 32.0

# Toggle Constants
ENABLE_DOG = True
ENABLE_ALIGNMENT = True
ENABLE_COHESION = True
ENABLE_SEPARATION = True
ENABLE_BOUNDARIES = True


DEBUGGING = True
DEBUG_LINE_WIDTH = 1
DEBUG_VELOCITY = DEBUGGING
DEBUG_BOUNDARIES = DEBUGGING
DEBUG_NEIGHBORS = DEBUGGING
DEBUG_DOG_INFLUENCE = DEBUGGING
DEBUG_BOUNDING_RECTS = DEBUGGING