from Vector import Vector

# Constants that will be accessed throughout project
# World Constants
FRAME_RATE = 60
WORLD_WIDTH = 800
WORLD_HEIGHT = 600
BACKGROUND_COLOR = (100, 149, 237)
SCREEN_SIZE = Vector(WORLD_WIDTH, WORLD_HEIGHT)

# Player Constants
PLAYER_SIZE = 10.0
PLAYER_SPEED = 5.5
PLAYER_COLOR = (255, 229, 44)
PLAYER_WEIGHT = .5

# Enemy Constants
ENEMY_SIZE = 10.0
ENEMY_SPEED = 5
ENEMY_COLOR = (79, 201, 0)
MIN_ATTACK_DIST = 200
ENEMY_FLEE_WEIGHT = .5
ENEMEY_WANDER_WEIGHT = .5

# Agent Constants
AGENT_WIDTH = 16.0
AGENT_HEIGHT = 32.0
